---
- name: CrowdStrike Falcon | Authenticate to CrowdStrike API
  uri:
    url: "https://{{ falcon_api_url }}/oauth2/token"
    method: POST
    body_format: json
    body: 
      "client_id={{ falcon_api_client_id }}&client_secret={{ falcon_api_client_secret }}"
    return_content: true
    status_code: 201
    headers:
        content-type: application/x-www-form-urlencoded
  register: falcon_api_oauth2_token

- name: CrowdStrike Falcon | Detect Target CID Based on Credentials
  uri:
    url: https://{{ falcon_api_url }}/sensors/queries/installers/ccid/v1
    method: GET
    return_content: true
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
      Content-Type: application/json
  register: falcon_api_target_cid

- name: CrowdStrike Falcon | Detect SHA256 of Latest Linux Sensor
  uri:
    url: "https://{{ falcon_api_url }}/sensors/combined/installers/v1?filter=platform%3A%22{{ falcon_os_family }}*%22%2Bos%3A%22{{ falcon_target_os }}%22&=&sort=version.desc&limit=1"
    method: GET
    return_content: true
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  register: falcon_api_sha_hash

- name: CrowdStrike Falcon | Detect Name of Latest Linux Sensor
  uri:
    url: "https://{{ falcon_api_url }}/sensors/combined/installers/v1?filter=platform%3A%22{{ falcon_os_family }}*%22%2Bos%3A%22{{ falcon_target_os }}%22&=&sort=version.desc&limit=1"
    method: GET
    return_content: true
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  register: falcon_api_installer_version

- name: CrowdStrike Falcon | Download Latest Sensor Installation Package
  get_url:
    url: https://{{ falcon_api_url }}/sensors/entities/download-installer/v1?id={{ falcon_api_sha_hash.json.resources[0].sha256 }}
    dest: "{{ falcon_install_tmp_dir }}"
    checksum: "sha256:{{ falcon_api_sha_hash.json.resources[0].sha256 }}"
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  register: falcon_sensor_download

- set_fact:
    falcon_cid: "{{ falcon_api_target_cid.json.resources[0] }}"
  when: not falcon_cid

- set_fact:
    non_win_pkg: "{{ falcon_sensor_download.dest }}"
