---
- block:
  - name: "CrowdStrike Falcon | Validate Required API URL Is Defined"
    fail:
      msg: "falcon_api_url is not configured! Please configure falcon_api_url and re-run the installation again!"
    when: not falcon_api_url
 
  - name: CrowdStrike Falcon | Validate CrowdStrike API Client ID Is Defined
    fail:
      msg: falcon_api_client_id is not configured! Please configure falcon_api_client_id and re-run the installation again!
    when: not falcon_api_client_id

  - name: CrowdStrike Falcon | Validate CrowdStrike API Client Secret Is Defined
    fail:
      msg: falcon_api_client_secret is not configured! Please configure falcon_api_client_secret and re-run the installation again!
    when: not falcon_api_client_secret

  when: falcon_install_method == "api"

- name: CrowdStrike Falcon | Determine Target OS
  set_fact:
     falcon_target_os: RHEL/CentOS/Oracle
     falcon_os_family: linux
  when: ansible_os_family == "RedHat"

- name: CrowdStrike Falcon | Determine Target OS
  set_fact:
    falcon_target_os: SLES
    falcon_os_family: linux
  when: ansible_distribution == "SLES"

- set_fact:
    installed_sensor: falcon-sensor
  when:
    - ansible_pkg_mgr in linux_packagers

- set_fact:
    non_win_pkg: "{{ installed_sensor }}"
  when:
    - ansible_pkg_mgr in linux_packagers
    - falcon_sensor_download is not defined

- set_fact:
    falcon_install_tmp_dir: /tmp/
  when:
    - not falcon_install_tmp_dir
    - ansible_system == "Linux" or ansible_system == "Darwin"

- name: CrowdStrike Falcon | Verify Temporary Install Directory Exists
  file:
    path: "{{ falcon_install_tmp_dir }}"
    state: directory
  when: falcon_install_tmp_dir
